### PR TITLE
Added HackNotts 2015 to the calendar

### PR DESCRIPTION
**Pull request by jamietanna**

### CODE REVIEW

**Comment by japacible** [comment]
Please move this to README.md instead of Past-Hackathons.md. Also, the date isn't listed on the website yet; is it finalized?

**Comment by jamietanna** [comment]
Apologies for that, should be moved now. And yes it is - we need to update the website with that, but I can confirm that as per [the official MLH EU schedule](https://mlh.io/seasons/f2015-eu/events) HackNotts will be 28th-29th November

**Comment by japacible** [comment]
Thanks! One more thing - please list HackNotts alphabetically for Nov 28 starts, so just above Innovation Drive for Impact.

**Comment by jamietanna** [comment]
Sorry about that! Should be all done now.

**Comment by japacible** [comment]
Above "Innovation Drive for Impact", please. Thanks! =)

**Comment by jamietanna** [comment]
I guess I need to practice my ABC :)

**Comment by japacible** [comment]
=)

**Pull request merged**
